export const Leadership = [
  "chaired",
  "controlled",
  "coordinated",
  "executed",
  "headed",
  "operated",
  "orchestrated",
  "organized",
  "oversaw",
  "planned",
  "produced",
  "programmed",
  "aligned",
  "cultivated",
  "directed",
  "enabled",
  "facilitated",
  "fostered",
  "guided",
  "hired",
  "inspired",
  "mentored",
  "mobilized",
  "motivated",
  "recruited",
  "regulated",
  "shaped",
  "supervised",
  "taught",
  "trained",
  "unified",
  "united"
];

export const Initiative = [
  "administered",
  "built",
  "charted",
  "created",
  "designed",
  "developed",
  "devised",
  "founded",
  "engineered",
  "established",
  "formalized",
  "formed",
  "formulated",
  "implemented",
  "incorporated",
  "initiated",
  "instituted",
  "introduced",
  "launched",
  "pioneered",
  "spearheaded"
];

export const Optimization = [
  "conserved",
  "consolidated",
  "decreased",
  "deducted",
  "diagnosed",
  "lessened",
  "reconciled",
  "reduced",
  "yielded",
  "accelerated",
  "achieved",
  "advanced",
  "amplified",
  "boosted",
  "capitalized",
  "delivered",
  "enhanced",
  "expanded",
  "expedited",
  "furthered",
  "gained",
  "generated",
  "improved",
  "lifted",
  "maximized",
  "outpaced",
  "stimulated",
  "sustained",
  "centralized",
  "clarified",
  "converted",
  "customized",
  "cnfluenced",
  "cntegrated",
  "merged",
  "modified",
  "overhauled",
  "redesigned",
  "refined",
  "refocused",
  "rehabilitated",
  "remodeled",
  "reorganized",
  "replaced",
  "restructured",
  "revamped",
  "revitalized",
  "simplified",
  "standardized",
  "streamlined",
  "strengthened",
  "updated",
  "upgraded",
  "transformed",
  "secured"
];

export const CustomerService = [
  "advised",
  "advocated",
  "arbitrated",
  "coached",
  "consulted",
  "educated",
  "fielded",
  "informed"
];

export const TeamOriented = [
  "aligned",
  "cultivated",
  "directed",
  "enabled",
  "facilitated",
  "fostered",
  "guided",
  "hired",
  "inspired",
  "mentored",
  "mobilized",
  "motivated",
  "recruited",
  "regulated",
  "shaped",
  "supervised",
  "taught",
  "trained",
  "unified",
  "united",
  "resolved",
  "navigated",
  "negotiated",
  "partnered"
];

export const ResearchOriented = [
  "analyzed",
  "assembled",
  "assessed",
  "audited",
  "calculated",
  "discovered",
  "evaluated",
  "examined",
  "explored",
  "forecasted",
  "identified",
  "interpreted",
  "investigated",
  "mapped",
  "measured",
  "qualified",
  "quantified",
  "surveyed",
  "tested",
  "tracked"
];

export const Achievement = [
  "attained",
  "awarded",
  "completed",
  "demonstrated",
  "earned",
  "exceeded",
  "outperformed",
  "reached",
  "showcased",
  "succeeded",
  "surpassed",
  "targeted"
];
export const Communication = [
  "authored",
  "briefed",
  "campaigned",
  "co-authored",
  "composed",
  "conveyed",
  "convinced",
  "corresponded",
  "counseled",
  "critiqued",
  "defined",
  "documented",
  "edited",
  "illustrated",
  "lobbied",
  "persuaded",
  "promoted",
  "publicized",
  "reviewed",
  "acquired",
  "forged"
];


// Stop Words //
const client = Algorithmia.client("simCnX5SgvLeu7IMGCGgT0GWnE41");
let input = [];
const stopWords
Algorithmia.client("simCnX5SgvLeu7IMGCGgT0GWnE41")
           .algo("algo://nlp/RetrieveStopWords/0.1.1")
           .pipe(input)
           .then(function(output) {
             stopWords = output;
             console.log(output);
           });

stopWords = stopWords.result;
